
#include "sys.h"
#include "MyUDP.h"
#include <AppDelay.h>
//////////////////////////////////////////////////////////////////////////////////	 
//IP phone
//GPIO 输出驱动代码	   
//创建日期:2018-9-6 10:37:09
//编写：Wang Qingwu
//版本：V1.0
//修改：
////////////////////////////////////////////////////////////////////////////////// 	

//下面的方式是通过位带操作方式读取IO
//#define KEY0        PHin(3) //KEY0按键PH3
//#define KEY1        PHin(2) //KEY1按键PH2
//#define KEY2        PCin(13)//KEY2按键PC13
//#define WK_UP       PAin(0) //WKUP按键PA0


//下面的方式是通过直接操作HAL库函数方式读取IO
//#define KEY0        HAL_GPIO_ReadPin(GPIOH,GPIO_PIN_3)  //KEY0按键PH3
//#define KEY1        HAL_GPIO_ReadPin(GPIOH,GPIO_PIN_2)  //KEY1按键PH2
//#define KEY2        HAL_GPIO_ReadPin(GPIOC,GPIO_PIN_13) //KEY2按键PC13
//#define WK_UP       HAL_GPIO_ReadPin(GPIOA,GPIO_PIN_0)  //WKUP按键PA0

#define DDD0        HAL_GPIO_ReadPin(GPIOA,GPIO_PIN_8)  //DDD0-PA8
#define DDD1        HAL_GPIO_ReadPin(GPIOA,GPIO_PIN_11)  //DDD1-PA11
#define DDD2        HAL_GPIO_ReadPin(GPIOA,GPIO_PIN_12) //DDD2-PA12
#define DDD3       	HAL_GPIO_ReadPin(GPIOC,GPIO_PIN_10)  //DDD3-PC10
#define DD_VAILD    HAL_GPIO_ReadPin(GPIOC,GPIO_PIN_11)  //DDD3-PC111

#define DIL_VAILD    HAL_GPIO_ReadPin(GPIOD,GPIO_PIN_8)  //DIL-PD8

#define nRESET_IP178_0 HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,GPIO_PIN_RESET)   ///PB0置1，作为IP178复位脚
#define nRESET_IP178_1 HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,GPIO_PIN_SET)   ///PB0置1，作为IP178复位脚

#define KEY_LED1_ENABLE			HAL_GPIO_WritePin(GPIOD,GPIO_PIN_0,GPIO_PIN_RESET);		//PD0置0,开
#define KEY_LED1_DISABLE		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_0,GPIO_PIN_SET);			//PD0置1，关

#define DEBUG_LED_ENABLE		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_13,GPIO_PIN_RESET);	//PD13置0
#define DEBUG_LED_DISABLE		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_13,GPIO_PIN_SET);		//PD13置1
#define HT9200B_nCE_ENABLE	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_14,GPIO_PIN_RESET); 	//PD14置0
#define HT9200B_nCE_DISABLE	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_14,GPIO_PIN_SET); 		//PD14置1

#define DTMFD0_RESET HAL_GPIO_WritePin(GPIOD,GPIO_PIN_15,GPIO_PIN_RESET);	//PD15置0,DTMF/D0
#define DTMFD1_RESET HAL_GPIO_WritePin(GPIOC,GPIO_PIN_6,GPIO_PIN_RESET);	//PC6置1,DTMF/D1
#define DTMFD2_RESET HAL_GPIO_WritePin(GPIOC,GPIO_PIN_7,GPIO_PIN_RESET);	//PC7置1,DTMF/D2
#define DTMFD3_RESET HAL_GPIO_WritePin(GPIOC,GPIO_PIN_8,GPIO_PIN_RESET);	//PC8置1,DTMF/D3

#define DTMFD0_SET HAL_GPIO_WritePin(GPIOD,GPIO_PIN_15,GPIO_PIN_SET);	//PD15置0,DTMF/D0
#define DTMFD1_SET HAL_GPIO_WritePin(GPIOC,GPIO_PIN_6,GPIO_PIN_SET);	//PC6置1,DTMF/D1
#define DTMFD2_SET HAL_GPIO_WritePin(GPIOC,GPIO_PIN_7,GPIO_PIN_SET);	//PC7置1,DTMF/D2
#define DTMFD3_SET HAL_GPIO_WritePin(GPIOC,GPIO_PIN_8,GPIO_PIN_SET);	//PC8置1,DTMF/D3

#define LCD_RS_0	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_0,GPIO_PIN_RESET);		//PE0置0
#define LCD_RS_1	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_0,GPIO_PIN_SET);			//PE0置1
#define LCD_RW_0	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_1,GPIO_PIN_RESET);		//PE1置0
#define LCD_RW_1	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_1,GPIO_PIN_SET);			//PE1置1
#define LCD_E_0		HAL_GPIO_WritePin(GPIOE,GPIO_PIN_2,GPIO_PIN_RESET);		//PE2置0
#define LCD_E_1		HAL_GPIO_WritePin(GPIOE,GPIO_PIN_2,GPIO_PIN_SET);			//PE2置1
#define LCD_D4_0	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_3,GPIO_PIN_RESET);		//PE3置0
#define LCD_D4_1	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_3,GPIO_PIN_SET);			//PE3置1
#define LCD_D5_0	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_4,GPIO_PIN_RESET);		//PE4置0
#define LCD_D5_1	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_4,GPIO_PIN_SET);			//PE4置1
#define LCD_D6_0	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_5,GPIO_PIN_RESET);		//PE5置0
#define LCD_D6_1	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_5,GPIO_PIN_SET);			//PE5置1
#define LCD_D7_0	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_6,GPIO_PIN_RESET);		//PE6置0
#define LCD_D7_1	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_6,GPIO_PIN_SET);			//PE6置1

#define JDQ1_DISABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_7,GPIO_PIN_RESET);		//PE7置0
#define JDQ2_DISABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_8,GPIO_PIN_RESET);		//PE8置0
#define JDQ3_DISABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_9,GPIO_PIN_RESET);		//PE9置0
#define JDQ4_DISABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_10,GPIO_PIN_RESET);	//PE10置0
#define JDQ5_DISABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_11,GPIO_PIN_RESET);	//PE11置0
#define JDQ6_DISABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_12,GPIO_PIN_RESET);	//PE12置0
#define JDQ7_DISABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_13,GPIO_PIN_RESET);	//PE13置0
#define JDQ8_DISABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_14,GPIO_PIN_RESET);	//PE14置0

#define JDQ1_ENABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_7,GPIO_PIN_SET);			//PE7置1
#define JDQ2_ENABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_8,GPIO_PIN_SET);			//PE8置1
#define JDQ3_ENABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_9,GPIO_PIN_SET);			//PE9置1
#define JDQ4_ENABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_10,GPIO_PIN_SET);		//PE10置1
#define JDQ5_ENABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_11,GPIO_PIN_SET);		//PE11置1
#define JDQ6_ENABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_12,GPIO_PIN_SET);		//PE12置1
#define JDQ7_ENABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_13,GPIO_PIN_SET);		//PE13置1
#define JDQ8_ENABLE	HAL_GPIO_WritePin(GPIOE,GPIO_PIN_14,GPIO_PIN_SET);		//PE14置1

///////////矩阵键盘////////////////////////////
//输入
#define K0_Value   HAL_GPIO_ReadPin(GPIOB,GPIO_PIN_9) //K0-PB9
#define K1_Value   HAL_GPIO_ReadPin(GPIOB,GPIO_PIN_8) //K1-PB8
#define K2_Value   HAL_GPIO_ReadPin(GPIOC,GPIO_PIN_2) //K2-PC2
#define K3_Value   HAL_GPIO_ReadPin(GPIOC,GPIO_PIN_3) //K3-PC3

//输出
#define K8_RESET		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_RESET);		//PD2置0
#define K7_RESET		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_3,GPIO_PIN_RESET);		//PD3置0
#define K6_RESET		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_4,GPIO_PIN_RESET);		//PD4置0
#define K5_RESET		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_6,GPIO_PIN_RESET);		//PD6置0
#define K4_RESET		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_7,GPIO_PIN_RESET);		//PD7置0
#define K8_SET			HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_SET);			//PD2置1
#define K7_SET			HAL_GPIO_WritePin(GPIOD,GPIO_PIN_3,GPIO_PIN_SET);			//PD3置1
#define K6_SET			HAL_GPIO_WritePin(GPIOD,GPIO_PIN_4,GPIO_PIN_SET);			//PD4置1
#define K5_SET			HAL_GPIO_WritePin(GPIOD,GPIO_PIN_6,GPIO_PIN_SET);			//PD6置1
#define K4_SET			HAL_GPIO_WritePin(GPIOD,GPIO_PIN_7,GPIO_PIN_SET);			//PD7置1

//////输入 摘机检测//
#define HAND_ONnOFF_Value   HAL_GPIO_ReadPin(GPIOD,GPIO_PIN_1) //HAND_ONnOFF-PD1

/////输出到FPGA,通话模式选择，提示音选择，模式选择/////
#define PCM3_ETHnP_RESET		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_10,GPIO_PIN_RESET);	//PCM3置0
#define PCM2_MUSIC2_RESET		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_11,GPIO_PIN_RESET);	//PCM2置0
#define PCM1_MUSIC1_RESET		HAL_GPIO_WritePin(GPIOD,GPIO_PIN_12,GPIO_PIN_RESET);	//PCM1置0
#define SEL_BRCnN_RESET			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_14,GPIO_PIN_RESET);	//MCU_BAKIO11置0
#define ENABLE_RESET				HAL_GPIO_WritePin(GPIOB,GPIO_PIN_15,GPIO_PIN_RESET);	//MCU_BAKIO12置0
	
#define PCM3_ETHnP_SET			HAL_GPIO_WritePin(GPIOD,GPIO_PIN_10,GPIO_PIN_SET);	//PCM3置1
#define PCM2_MUSIC2_SET			HAL_GPIO_WritePin(GPIOD,GPIO_PIN_11,GPIO_PIN_SET);	//PCM2置1
#define PCM1_MUSIC1_SET			HAL_GPIO_WritePin(GPIOD,GPIO_PIN_12,GPIO_PIN_SET);	//PCM1置1
#define SEL_BRCnN_SET				HAL_GPIO_WritePin(GPIOB,GPIO_PIN_14,GPIO_PIN_SET);	//MCU_BAKIO11置1 
#define ENABLE_SET					HAL_GPIO_WritePin(GPIOB,GPIO_PIN_15,GPIO_PIN_SET);	//MCU_BAKIO12置1

void phone_num(void);
unsigned char Read44KeyValue(void);
void dil_phone_num(void);
void HT9200B_CTRL(u8 num);
